#define ALARMA_TIME_PERIOD 50 //En ms

#define ALARMA_ARMING_TIME_LAPSE 60000 //En ms
#define ALARMA_INTRUDER_TIME_LAPSE 60000 //En ms

#define ALARMA_ARMING_TICK_LAPSE ALARMA_ARMING_TIME_LAPSE/ALARMA_TIME_PERIOD ///En Ticks
#define ALARMA_INTRUDER_TICK_LAPSE ALARMA_INTRUDER_TIME_LAPSE/ALARMA_TIME_PERIOD///En ticks

typedef enum {
	ALARM_DISARMED = 0,
	ALARM_ARMING,
	ALARM_ARMED,
	ALARM_DISARMING,
	ALARM_INTRUDER
} fsmAlarmaState_t;

void alarmaInit (void);
void alarmaUpdate (void);
